[package]
name = "yablo"
version = "0.1.0"
authors = ["Sebastian Jung <git.sebastian@gmx.de>"]
edition = "2018"

[dependencies]
num_cpus = "1.13.0"
clap = "2.33.3"
battery = "0.7.6"
nix = "0.18.0"
systemstat = "0.1.5"
toml = "0.5.6"
serde = "1.0.115"
serde_derive = "1.0.115"
crossterm = "0.17.7"
